# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 092696dfbe1b4a168ebf539db1a9df4b2167157eab107fe503fe89be99ff54096daa49cf3a5c3ca27234d3d376ae549df85589bcbc5e8e5eea8a30583fb232b9

test:
  secret_key_base: 97906dcd8ab0d90476605ea2e541f03201b551fd836e08cdf404c7c94f0bde78db29237b4b2a85228dde88100c778e925dbd63bc39f5557a4e9d058f6a2f707f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
